"""Dependency-free, deterministic static publishing. No external side effects."""
from __future__ import annotations

from contextlib import contextmanager
from datetime import date
import hashlib
import html
from html.parser import HTMLParser
import json
import os
from pathlib import Path
import re
from string import Template
import tempfile
from urllib.parse import quote, unquote, urlencode, urlsplit

RESOURCES = Path(__file__).resolve().parent / "resources"
SLUG = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*\Z")
MARKER = b"<!-- Generated by PhantomBlog v1 -->"
MANIFEST = "phantomblog-manifest.json"
ARCHIVE = re.compile(r"blog(?:-es)?-page-([2-9]|[1-9][0-9]+)\.html\Z")
LANGUAGES = ("en", "es")
LABELS = {
    "en": {"archive": "Articles", "read": "Read article", "previous": "Previous", "next": "Next", "share": "Share", "empty": "No articles published yet", "date": "Published", "featured": "Featured"},
    "es": {"archive": "Artículos", "read": "Leer artículo", "previous": "Anterior", "next": "Siguiente", "share": "Compartir", "empty": "Todavía no hay artículos publicados", "date": "Publicado", "featured": "Destacado"},
}


class Invalid(ValueError):
    """Invalid source or unsafe ownership; exit code 2."""


class Conflict(Invalid):
    """Another editor saved a newer revision."""


def digest(data):
    return hashlib.sha256(data).hexdigest()


def encoded(value):
    return (json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True, allow_nan=False) + "\n").encode("utf-8")


def decode(data):
    def unique(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise Invalid(f"Duplicate JSON key: {key}")
            result[key] = value
        return result
    try:
        if isinstance(data, bytes):
            data = data.decode("utf-8")
        return json.loads(data, object_pairs_hook=unique, parse_constant=lambda v: (_ for _ in ()).throw(Invalid(f"Invalid JSON constant: {v}")))
    except (ValueError, UnicodeError) as exc:
        raise Invalid("Invalid UTF-8 JSON") from exc


def contained(root, name, exists=False):
    if not isinstance(name, str) or not name or "\\" in name or any(ord(c) < 32 for c in name):
        raise Invalid("Expected a relative POSIX path")
    if any(p in ("", ".", "..") for p in name.split("/")) or any(c in name for c in ":%?#"):
        raise Invalid(f"Unsafe path: {name}")
    root = root.resolve()
    result = root / name
    if not result.resolve().is_relative_to(root):
        raise Invalid(f"Path escapes project: {name}")
    # Refuse symlink components even if they point inside: ownership is lexical.
    if any(p.is_symlink() for p in [result, *result.parents] if p != root and p.is_relative_to(root)):
        raise Invalid(f"Symlinks are not owned: {name}")
    if exists and not result.is_file():
        raise Invalid(f"Missing file: {name}")
    return result


def plain(value, label):
    if not isinstance(value, str) or not value.strip() or len(value) > 5000 or any(ord(c) < 32 for c in value):
        raise Invalid(f"{label}: expected nonempty plain text")
    return value


def slug(value):
    if not isinstance(value, str) or not SLUG.fullmatch(value) or len(value) > 100:
        raise Invalid("Slugs use lowercase letters, digits and single hyphens")
    return value


def valid_date(value):
    if not isinstance(value, str) or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
        raise Invalid("Dates must use YYYY-MM-DD")
    try:
        return date.fromisoformat(value)
    except ValueError as exc:
        raise Invalid("Invalid calendar date") from exc


def http_url(value, local=False):
    if not isinstance(value, str) or any(ord(c) <= 32 for c in value) or "\\" in value:
        raise Invalid("Invalid URL")
    parts = urlsplit(value)
    if parts.scheme not in (("http", "https") if local else ("https",)) or not parts.hostname or parts.username or parts.password:
        raise Invalid("Expected an HTTPS URL without credentials")
    return parts


def local_url(value, root, planned):
    if not isinstance(value, str) or not value or "\\" in value or any(ord(c) <= 32 for c in value):
        raise Invalid("Invalid body URL")
    parts = urlsplit(value)
    if parts.scheme or parts.netloc:
        http_url(value)
    elif parts.path:
        name = unquote(parts.path).removeprefix("/")
        if name not in planned and not contained(root / "assets", name, exists=True).is_file():
            raise Invalid("Missing body asset")


class Fragment(HTMLParser):
    TAGS = set("p h2 h3 h4 h5 h6 ul ol li dl dt dd table caption colgroup col thead tbody tfoot tr th td figure figcaption img a em strong b i u s small sup sub br hr div span section aside blockquote pre code abbr time details summary".split())
    VOID = {"img", "br", "hr", "col"}
    ATTRS = set("id class title lang dir role href src cite alt width height loading decoding target rel scope headers colspan rowspan span datetime start reversed value open abbr".split())

    def __init__(self, root, planned):
        super().__init__(convert_charrefs=True)
        self.root, self.planned = root, planned
        self.stack, self.ids, self.anchors = [], set(), []
        self.assets = set()

    def handle_decl(self, _):
        raise Invalid("Document declarations are not body fragments")

    def handle_pi(self, _):
        raise Invalid("Processing instructions are forbidden")

    def unknown_decl(self, _):
        raise Invalid("Embedded declarations are forbidden")

    def handle_starttag(self, tag, attrs):
        if tag not in self.TAGS:
            raise Invalid(f"Unsupported body element: {tag}")
        if len(dict(attrs)) != len(attrs):
            raise Invalid("Duplicate body attribute")
        a = dict(attrs)
        for key, value in attrs:
            if key not in self.ATTRS and not key.startswith("aria-"):
                raise Invalid(f"Unsupported body attribute: {key}")
            if key in ("href", "src", "cite"):
                local_url(value, self.root, self.planned)
                parts = urlsplit(value)
                if key == "src" and not parts.path:
                    raise Invalid("Body image src needs a file or HTTPS image path")
                if parts.path and not parts.scheme and not parts.netloc and unquote(parts.path).removeprefix("/") not in self.planned:
                    self.assets.add(unquote(parts.path).removeprefix("/"))
                if value.startswith("#"):
                    self.anchors.append(unquote(value[1:]))
            if key == "id":
                if not value or value in self.ids or value in ("site-nav", "content"):
                    raise Invalid("Duplicate or reserved body ID")
                self.ids.add(value)
        if tag == "img" and (not a.get("src") or not a.get("alt", "").strip()):
            raise Invalid("Body images need src and alt")
        if a.get("target") == "_blank" and "noopener" not in a.get("rel", "").split():
            raise Invalid("External tabs need rel=noopener")
        if tag not in self.VOID:
            self.stack.append(tag)

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if tag not in self.VOID:
            self.handle_endtag(tag)

    def handle_endtag(self, tag):
        if not self.stack or self.stack.pop() != tag:
            raise Invalid(f"Unbalanced closing body tag: {tag}")

    def validate(self, body):
        if not isinstance(body, str) or len(body.encode("utf-8")) > 1_000_000 or "\x00" in body:
            raise Invalid("Body must be HTML text under 1 MB")
        self.feed(body)
        self.close()
        if self.stack or any(a not in self.ids for a in self.anchors):
            raise Invalid("Unclosed body tags or missing anchors")


def scoped_css(css, scope):
    """A deliberately small CSS subset: flat selector/declaration rules only."""
    if not isinstance(css, str) or len(css) > 100_000:
        raise Invalid("CSS must be text under 100 KB")
    clean = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    if re.search(r"@|url\s*\(|expression\s*\(|[<>\\]", clean, re.I):
        raise Invalid("Custom CSS cannot import resources, use at-rules, escapes or markup")
    rules, pos = [], 0
    for match in re.finditer(r"([^{}]+)\{([^{}]*)\}", clean):
        if clean[pos:match.start()].strip():
            raise Invalid("Malformed CSS")
        selectors, declarations = match.groups()
        selected = []
        for selector in selectors.split(","):
            selector = selector.strip()
            if not selector or re.search(r":(?:root|has|host)|\b(?:html|body)\b", selector, re.I):
                raise Invalid("Selectors must address article content")
            selected.append(f"{scope} {selector}")
        rules.append(", ".join(selected) + " {" + declarations + "}")
        pos = match.end()
    if clean[pos:].strip():
        raise Invalid("Malformed CSS")
    return "\n".join(rules)


def validate_design(design, root=None):
    if not isinstance(design, dict) or set(design) - {"layout", "accent", "css", "sections", "templateFile"}:
        raise Invalid("Unknown design option")
    if design.get("layout", "classic") not in ("classic", "editorial", "compact"):
        raise Invalid("Unknown article layout")
    if not isinstance(design.get("accent", "#7253cc"), str) or not re.fullmatch(r"#[a-fA-F0-9]{6}", design.get("accent", "#7253cc")):
        raise Invalid("Accent must be a six digit hex colour")
    sections = design.get("sections", ["cover", "lead", "body"])
    if not isinstance(sections, list) or len(sections) != 3 or any(not isinstance(s, str) for s in sections) or sorted(sections) != ["body", "cover", "lead"]:
        raise Invalid("Sections must contain cover, lead and body exactly once")
    scoped_css(design.get("css", ""), ".pb-article")
    if root is not None and "templateFile" in design:
        template = contained(root / "templates", design["templateFile"], True).read_text(encoding="utf-8")
        validate_template(template)


def article_url(article, lang):
    if article.get("mode", "generated") == "legacy":
        return article[lang]["url"]
    return "blog-" + article["slug"] + ("-es" if lang == "es" else "") + ".html"


def archive_url(lang, page=1):
    return "blog" + ("-es" if lang == "es" else "") + (f"-page-{page}" if page > 1 else "") + ".html"


def source_body(root, translation):
    if "bodyFile" in translation and "body" in translation:
        raise Invalid("Use body or bodyFile, not both")
    if "bodyFile" in translation:
        return contained(root / "bodies", translation["bodyFile"], exists=True).read_text(encoding="utf-8")
    return translation.get("body", "")


def validate(root, model, include_drafts=False):
    for directory in ("assets", "bodies", "templates", "public"):
        contained(root, directory)
    if not isinstance(model, dict) or set(model) != {"schemaVersion", "site", "theme", "categories", "articles", "connections"} or type(model["schemaVersion"]) is not int or model["schemaVersion"] != 1:
        raise Invalid("Expected PhantomBlog schemaVersion 1")
    site = model["site"]
    if not isinstance(site, dict) or set(site) != {"name", "url", "description"}:
        raise Invalid("Site needs name, url and bilingual description")
    plain(site["name"], "Site name")
    if not isinstance(site["description"], dict) or set(site["description"]) != set(LANGUAGES):
        raise Invalid("Site description needs en and es")
    parts = http_url(site["url"])
    if parts.query or parts.fragment or not site["url"].endswith("/"):
        raise Invalid("Site URL must end with / and have no query or fragment")
    for lang in LANGUAGES:
        plain(site["description"].get(lang), f"Site description {lang}")
    validate_design(model["theme"], root)
    if "templateFile" in model["theme"]:
        contained(root / "templates", model["theme"]["templateFile"], exists=True)
    if not isinstance(model["categories"], list) or not isinstance(model["articles"], list):
        raise Invalid("Categories and articles must be arrays")
    categories = set()
    for category in model["categories"]:
        if not isinstance(category, dict) or set(category) - {"slug", "en", "es", "design"} or not {"slug", "en", "es"}.issubset(category):
            raise Invalid("Invalid category record")
        key = slug(category["slug"])
        if key in categories:
            raise Invalid("Duplicate category")
        categories.add(key)
        for lang in LANGUAGES:
            plain(category.get(lang), "Category label")
        validate_design(category.get("design", {}), root)
    planned, keys = set(), set()
    for a in model["articles"]:
        if not isinstance(a, dict) or set(a) - {"slug", "category", "status", "mode", "publishedAt", "updatedAt", "featured", "image", "socialImage", "en", "es", "design"} or not {"slug", "category", "status", "publishedAt", "en", "es"}.issubset(a):
            raise Invalid("Unknown article field")
        key = slug(a["slug"])
        if key in keys:
            raise Invalid("Duplicate article slug")
        keys.add(key)
        if a.get("mode", "generated") not in ("generated", "legacy") or a.get("status") not in ("draft", "published"):
            raise Invalid("Article mode/status invalid")
        if a.get("category") not in categories:
            raise Invalid("Article category does not exist")
        published = valid_date(a.get("publishedAt"))
        if "updatedAt" in a and valid_date(a["updatedAt"]) < published:
            raise Invalid("updatedAt precedes publishedAt")
        if type(a.get("featured", False)) is not bool:
            raise Invalid("featured must be boolean")
        validate_design(a.get("design", {}), root)
        if a.get("mode", "generated") == "generated":
            planned.update(article_url(a, lang) for lang in LANGUAGES)
    generated_planned = set(planned)
    public_count = sum(a["status"] == "published" for a in model["articles"])
    public_pages = max(1, (public_count + 11) // 12)
    public_planned = {urlsplit(article_url(a, l)).path for a in model["articles"] if a["status"] == "published" for l in LANGUAGES}
    public_planned.update(archive_url(l, p) for l in LANGUAGES for p in range(1, public_pages + 1))
    planned.update(public_planned)
    assets = {}
    for a in model["articles"]:
        for field in ("image", "socialImage"):
            name = a.get(field)
            if not name and a["status"] == "draft":
                continue
            path = contained(root / "assets", name, exists=True)
            data = path.read_bytes()
            if field == "socialImage" and not ((path.suffix.lower() == ".png" and data.startswith(b"\x89PNG\r\n\x1a\n")) or (path.suffix.lower() in (".jpg", ".jpeg") and data.startswith(b"\xff\xd8\xff")) or (path.suffix.lower() == ".webp" and data[:4] == b"RIFF" and data[8:12] == b"WEBP")):
                raise Invalid("Social images must be PNG, JPEG or WebP rasters")
            if path.suffix.lower() not in (".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"):
                raise Invalid("Unsupported image type")
            if include_drafts or a["status"] == "published":
                assets[name] = data
        for lang in LANGUAGES:
            t = a.get(lang)
            if not isinstance(t, dict) or set(t) - {"title", "summary", "description", "imageAlt", "lead", "body", "bodyFile", "url"}:
                raise Invalid(f"Missing/invalid {lang} translation")
            for field in ("title", "summary", "description", "imageAlt"):
                if a["status"] == "published" or t.get(field):
                    plain(t.get(field), f"{a['slug']} {lang} {field}")
            if a.get("mode", "generated") == "legacy":
                parts = urlsplit(t.get("url", ""))
                if parts.scheme or parts.netloc or not parts.path.endswith(".html"):
                    raise Invalid("Legacy URLs must reference existing local HTML")
                contained(root / "public", unquote(parts.path), exists=True)
                if parts.path in generated_planned:
                    raise Invalid("Legacy/generated URL collision")
            else:
                body = source_body(root, t)
                fragment = Fragment(root, planned if include_drafts or a["status"] == "draft" else public_planned)
                fragment.validate(body)
                for name in fragment.assets:
                    if name in {MANIFEST, "phantomblog.css"} or name.startswith("blog") and name.endswith(".html"):
                        raise Invalid("Body asset collides with generator output")
                    path = contained(root / "assets", name, True)
                    if path.suffix.lower() not in (".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg", ".pdf"):
                        raise Invalid("Unsupported body asset")
                    if include_drafts or a["status"] == "published":
                        assets[name] = path.read_bytes()
                if a["status"] == "published" and not body.strip():
                    raise Invalid("Published articles need authored bodies in both languages")
    from .connectors import validate_connections
    validate_connections(model["connections"])
    return assets


class Document(HTMLParser):
    VOID = {"area", "br", "col", "hr", "img", "input", "link", "meta", "source", "wbr"}

    def __init__(self):
        super().__init__()
        self.stack, self.counts = [], {}
        self.ids, self.lang = set(), None

    def handle_starttag(self, tag, attrs):
        if tag in ("script", "iframe", "object", "embed", "base", "form") or any(k.startswith("on") for k, _ in attrs):
            raise Invalid("Templates cannot contain active content; use HTML and scoped CSS")
        a = dict(attrs)
        if len(a) != len(attrs):
            raise Invalid("Duplicate template attribute")
        if tag == "html" and self.lang and a.get("lang") != self.lang:
            raise Invalid("Template must declare the generated page language")
        if tag in ("meta", "title", "link") and "head" not in self.stack:
            raise Invalid("Page metadata belongs inside head")
        if tag == "meta" and a.get("http-equiv", "").lower() == "refresh":
            raise Invalid("Templates cannot redirect the reader")
        for key, value in attrs:
            if key in ("href", "src", "cite", "action", "formaction", "poster"):
                if not isinstance(value, str) or any(ord(c) <= 32 for c in value) or "\\" in value:
                    raise Invalid("Unsafe template URL")
                parts = urlsplit(value)
                if parts.scheme and parts.scheme not in ("https", "mailto") or parts.netloc and not parts.scheme:
                    raise Invalid("Unsafe template URL scheme")
        if "id" in a:
            if not a["id"] or a["id"] in self.ids:
                raise Invalid("Duplicate document ID")
            self.ids.add(a["id"])
        self.counts[tag] = self.counts.get(tag, 0) + 1
        if tag not in self.VOID:
            self.stack.append(tag)

    def handle_endtag(self, tag):
        if not self.stack or self.stack.pop() != tag:
            raise Invalid("Unbalanced shared template")

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if tag not in self.VOID:
            self.handle_endtag(tag)

    def validate(self, page, lang=None):
        self.lang = lang
        self.feed(page)
        self.close()
        if self.stack or any(self.counts.get(k) != 1 for k in ("html", "head", "body", "title", "header", "main", "footer", "h1")):
            raise Invalid("Template must produce one complete semantic HTML document")


def esc(value):
    return html.escape(str(value), quote=True)


def share_links(url, title):
    links = {
        "Facebook": "https://www.facebook.com/sharer/sharer.php?" + urlencode({"u": url}),
        "LinkedIn": "https://www.linkedin.com/sharing/share-offsite/?" + urlencode({"url": url}),
        "X": "https://twitter.com/intent/tweet?" + urlencode({"url": url, "text": title}),
        "WhatsApp": "https://wa.me/?" + urlencode({"text": title + " " + url}),
        "Email": "mailto:?" + urlencode({"subject": title, "body": url}),
    }
    return " ".join(f'<a href="{esc(link)}" target="_blank" rel="noopener noreferrer">{name}</a>' for name, link in links.items())


def design_for(model, a):
    category = next(c for c in model["categories"] if c["slug"] == a["category"])
    return {**model["theme"], **category.get("design", {}), **a.get("design", {})}


def render(root, model, include_drafts=False):
    assets = validate(root, model, include_drafts)
    template = (contained(root / "templates", model["theme"]["templateFile"], True).read_text(encoding="utf-8") if "templateFile" in model["theme"] else (RESOURCES / "page.html").read_text(encoding="utf-8"))
    parsed = Template(template)
    if not parsed.is_valid() or set(parsed.get_identifiers()) != {"lang", "head", "header", "content", "footer"}:
        raise Invalid("Page template requires exactly $lang, $head, $header, $content and $footer")
    outputs = {"phantomblog.css": (RESOURCES / "site.css").read_bytes()}
    outputs.update((name, data) for name, data in assets.items())
    articles = sorted((a for a in model["articles"] if include_drafts or a["status"] == "published"), key=lambda a: (-valid_date(a["publishedAt"]).toordinal(), a["slug"]))
    total = max(1, (len(articles) + 11) // 12)

    def page(lang, name, alternate, title, description, content, image=None, is_article=False, template_name=None):
        canonical = model["site"]["url"] + quote(name, safe="/?=&")
        others = {lang: name, "es" if lang == "en" else "en": alternate}
        head = f'<title>{esc(title)} · {esc(model["site"]["name"])}</title>\n<meta name="description" content="{esc(description)}">\n<link rel="canonical" href="{esc(canonical)}">\n<link rel="stylesheet" href="phantomblog.css">\n'
        for language, target in sorted(others.items()):
            head += f'<link rel="alternate" hreflang="{language}" href="{esc(model["site"]["url"] + target)}">\n'
        head += f'<link rel="alternate" hreflang="x-default" href="{esc(model["site"]["url"] + others["en"])}">\n'
        head += f'<meta property="og:type" content="{"article" if is_article else "website"}"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(description)}"><meta property="og:url" content="{esc(canonical)}"><meta property="og:locale" content="{"en_US" if lang == "en" else "es_ES"}"><meta property="og:locale:alternate" content="{"es_ES" if lang == "en" else "en_US"}"><meta name="twitter:card" content="{"summary_large_image" if image else "summary"}">'
        if image:
            head += f'<meta property="og:image" content="{esc(model["site"]["url"] + image)}"><meta name="twitter:image" content="{esc(model["site"]["url"] + image)}">'
        header = f'<header><a class="brand" href="{archive_url(lang)}">{esc(model["site"]["name"])}</a><nav id="site-nav" aria-label="{"Navigation" if lang == "en" else "Navegación"}"><a href="{archive_url(lang)}">{LABELS[lang]["archive"]}</a><a href="{esc(alternate)}" hreflang="{"es" if lang == "en" else "en"}" lang="{"es" if lang == "en" else "en"}">{"Español" if lang == "en" else "English"}</a></nav></header>'
        footer = f'<footer>{esc(model["site"]["name"])}</footer>'
        selected = Template(contained(root / "templates", template_name, True).read_text(encoding="utf-8")) if template_name else parsed
        document = '<!doctype html>\n' + MARKER.decode() + '\n' + selected.substitute(lang=lang, head=head, header=header, content=content, footer=footer)
        Document().validate(document, lang)
        return document.encode("utf-8")

    for lang in LANGUAGES:
        other = "es" if lang == "en" else "en"
        for number in range(1, total + 1):
            cards = []
            for a in articles[(number - 1) * 12:number * 12]:
                t = a[lang]
                category = next(c for c in model["categories"] if c["slug"] == a["category"])
                image = f'<img src="{esc(a["image"])}" alt="{esc(t.get("imageAlt", ""))}" loading="lazy">' if a.get("image") else ""
                cards.append(f'<article class="blog-card{" featured" if a.get("featured") else ""}">{image}<p class="eyebrow">{esc(category[lang])} · <time datetime="{a["publishedAt"]}">{a["publishedAt"]}</time>{" · " + LABELS[lang]["featured"] if a.get("featured") else ""}</p><h2><a href="{esc(article_url(a, lang))}">{esc(t.get("title") or a["slug"])}</a></h2><p>{esc(t.get("summary", ""))}</p><a href="{esc(article_url(a, lang))}">{LABELS[lang]["read"]} →</a></article>')
            pagination = ""
            if number > 1:
                pagination += f'<a rel="prev" href="{archive_url(lang, number - 1)}">{LABELS[lang]["previous"]}</a>'
            pagination += f'<span>{number} / {total}</span>'
            if number < total:
                pagination += f'<a rel="next" href="{archive_url(lang, number + 1)}">{LABELS[lang]["next"]}</a>'
            content = f'<main id="content"><h1>{LABELS[lang]["archive"]}</h1><p>{esc(model["site"]["description"][lang])}</p><div class="blog-grid">{"".join(cards) or "<p>" + LABELS[lang]["empty"] + "</p>"}</div><nav class="pagination" aria-label="Pagination">{pagination}</nav></main>'
            name = archive_url(lang, number)
            outputs[name] = page(lang, name, archive_url(other, number), LABELS[lang]["archive"], model["site"]["description"][lang], content, articles[0].get("socialImage") if articles else None)
        for a in articles:
            if a.get("mode", "generated") == "legacy":
                continue
            t, design = a[lang], design_for(model, a)
            pieces = {"cover": f'<figure><img src="{esc(a["image"])}" alt="{esc(t.get("imageAlt", ""))}"></figure>' if a.get("image") else "", "lead": f'<p class="lead">{esc(t.get("lead", t.get("summary", "")))}</p>', "body": f'<div class="article-body">{source_body(root, t)}</div>'}
            css = scoped_css(model["theme"].get("css", ""), ".pb-article")
            category = next(c for c in model["categories"] if c["slug"] == a["category"])
            css += "\n" + scoped_css(category.get("design", {}).get("css", ""), ".pb-article")
            css += "\n" + scoped_css(a.get("design", {}).get("css", ""), ".pb-article")
            css += f'\n.pb-article {{ --article-accent: {design.get("accent", "#7253cc")}; }}'
            name = article_url(a, lang)
            content = f'<main id="content"><article class="pb-article {design.get("layout", "classic")}"><p class="eyebrow">{esc(category[lang])} · <time datetime="{a["publishedAt"]}">{a["publishedAt"]}</time></p><h1>{esc(t.get("title") or a["slug"])}</h1>{"".join(pieces[p] for p in design.get("sections", ["cover", "lead", "body"]))}<aside class="share"><h2>{LABELS[lang]["share"]}</h2>{share_links(model["site"]["url"] + name, t.get("title", a["slug"]))}</aside></article><style>{css}</style></main>'
            outputs[name] = page(lang, name, article_url(a, other), t.get("title") or a["slug"], t.get("description", ""), content, a.get("socialImage"), True, design.get("templateFile"))
    if len(outputs) != len(set(outputs)):
        raise Invalid("Output collision")
    return outputs


def validate_template(template):
    parsed = Template(template)
    if not parsed.is_valid() or set(parsed.get_identifiers()) != {"lang", "head", "header", "content", "footer"}:
        raise Invalid("Template requires $lang, $head, $header, $content and $footer")
    Document().validate(parsed.substitute(lang="en", head="<title>Validation</title>", header="<header></header>", content="<main><h1>Validation</h1></main>", footer="<footer></footer>"))


def atomic(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix=".phantomblog-", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(name, path)
    finally:
        if os.path.exists(name):
            os.unlink(name)


@contextmanager
def lock(root):
    path = contained(root, ".phantomblog-lock")
    try:
        fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    except FileExistsError as exc:
        raise Conflict("Workspace busy; another operation is in progress") from exc
    try:
        os.close(fd)
        yield
    finally:
        path.unlink(missing_ok=True)


def load(root):
    data = contained(root, "blog.json", True).read_bytes()
    return decode(data), digest(data)


def save(root, model, revision):
    with lock(root):
        old, current = load(root)
        if revision != current:
            raise Conflict("This draft changed elsewhere. Reload before saving.")
        # Existing published slugs/legacy URLs remain immutable; unpublish/archive
        # first. Published output deletion is always an explicit later decision.
        after = {a["slug"]: a for a in model.get("articles", [])}
        for a in old["articles"]:
            if a["status"] == "published" and a["slug"] not in after:
                raise Invalid("Published articles cannot be removed; change status to draft")
            if a.get("mode") == "legacy" and a["slug"] in after:
                b = after[a["slug"]]
                if b.get("mode") != "legacy" or any(b.get(l, {}).get("url") != a[l]["url"] for l in LANGUAGES):
                    raise Invalid("Legacy article URLs are immutable")
        render(root, model, include_drafts=True)
        data = encoded(model)
        atomic(contained(root, "blog.json"), data)
        return digest(data)


def build(root, mode="build", recover=False):
    if mode not in ("build", "check", "dry-run"):
        raise Invalid("Unknown build mode")
    model, revision = load(root)
    outputs = render(root, model)
    public = root / "public"
    manifest_path = contained(public, MANIFEST)
    old = {}
    if manifest_path.exists():
        previous = decode(manifest_path.read_bytes())
        if not isinstance(previous, dict) or set(previous) != {"generator", "version", "files"} or previous["generator"] != "phantomblog" or previous["version"] != 1 or not isinstance(previous["files"], dict):
            raise Invalid("Invalid output ownership manifest")
        old = previous["files"]
    for name, checksum in old.items():
        path = contained(public, name)
        if not isinstance(checksum, str) or not re.fullmatch(r"[0-9a-f]{64}", checksum):
            raise Invalid("Invalid manifest hash")
        if path.exists() and digest(path.read_bytes()) != checksum and not (recover and name in outputs and path.read_bytes() == outputs[name]):
            raise Invalid(f"Generated file edited outside the generator: {name}")
        if name.endswith(".html"):
            if not re.fullmatch(r"blog(?:-[a-z0-9]+)*\.html", name) or path.exists() and MARKER not in path.read_bytes()[:150]:
                raise Invalid(f"Manifest cannot claim a legacy or unrelated HTML page: {name}")
        elif name == "phantomblog.css":
            if path.exists() and not path.read_bytes().startswith(b"/* Generated by PhantomBlog v1 */"):
                raise Invalid("Stylesheet ownership marker missing")
        elif path.suffix.lower() not in (".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg", ".pdf"):
            raise Invalid("Manifest contains an unsupported output")
    for name, data in outputs.items():
        path = contained(public, name)
        if name in {MANIFEST, "blog.json"} or (path.exists() and name not in old):
            raise Invalid(f"Refusing to overwrite unowned file: {name}")
    deleted = []
    for name in old.keys() - outputs.keys():
        if ARCHIVE.fullmatch(name):
            path = contained(public, name)
            if path.exists():
                if MARKER not in path.read_bytes()[:150]:
                    raise Invalid("Obsolete archive ownership marker missing")
                deleted.append(name)
        else:
            # Retain old article URLs and assets; only numbered archives can be pruned.
            path = contained(public, name)
            if path.exists():
                outputs[name] = path.read_bytes()
    hashes = {name: digest(data) for name, data in sorted(outputs.items())}
    outputs[MANIFEST] = encoded({"generator": "phantomblog", "version": 1, "files": hashes})
    changed = sorted(name for name, data in outputs.items() if not contained(public, name).exists() or contained(public, name).read_bytes() != data)
    result = {"mode": mode, "changed": changed, "deleted": sorted(deleted), "urls": [model["site"]["url"] + name for name in sorted(outputs) if name.endswith(".html")], "liveVerified": False, "revision": revision}
    if mode == "build":
        with lock(root):
            if load(root)[1] != revision:
                raise Conflict("Source changed while rendering; retry")
            refreshed = render(root, load(root)[0])
            if any(outputs.get(name) != data for name, data in refreshed.items()):
                raise Conflict("Templates, assets or body sources changed while rendering")
            # Re-check ownership under the same lock used by source writers.
            for name in old:
                path = contained(public, name)
                if path.exists() and digest(path.read_bytes()) != old[name] and not (recover and name in outputs and path.read_bytes() == outputs[name]):
                    raise Conflict("Output changed while rendering")
            for name in changed:
                if name != MANIFEST and name not in old and contained(public, name).exists():
                    raise Conflict("An unowned output appeared while rendering")
            for name in changed:
                if name != MANIFEST:
                    atomic(contained(public, name), outputs[name])
            for name in deleted:
                contained(public, name).unlink()
            if MANIFEST in changed:
                atomic(manifest_path, outputs[MANIFEST])
    return result


def initial_model():
    return {"schemaVersion": 1, "site": {"name": "My publication", "url": "https://example.invalid/", "description": {"en": "Articles from our team.", "es": "Artículos de nuestro equipo."}}, "theme": {"layout": "classic", "accent": "#7253cc", "css": "", "sections": ["cover", "lead", "body"], "templateFile": "page.html"}, "categories": [{"slug": "guides", "en": "Guides", "es": "Guías", "design": {}}], "articles": [], "connections": {}}


def initialize(root):
    files = {"blog.json": encoded(initial_model()), "templates/page.html": (RESOURCES / "page.html").read_bytes(), "bodies/README.md": b"Optional authored HTML fragments: en/<slug>.html and es/<slug>.html. Reference with bodyFile.\n", "assets/README.md": b"Place authored card images and raster social previews here; reference their relative names.\n"}
    for name in files:
        if contained(root, name).exists():
            raise Invalid(f"Initialization would overwrite: {name}")
    for name, data in files.items():
        atomic(contained(root, name), data)
    return {"created": sorted(files)}
